name: dvc_starter
channels:
  - anaconda
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - dvc-gdrive
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - pytest
      - requests
      - fastapi==0.63.0
      - uvicorn